service: fraudstop

provider:
  name: aws
  iamRoleStatements:
  - Effect: Allow
    Action:
      - lambda:InvokeFunction
    Resource: "*"

functions:
  fraudstop-func:
    runtime: haskell
    handler: fraudstop.fraudstop-exe

  letter-func:
    runtime: nodejs10.x
    handler: letter.handler

package:
  include:
    - node_modules/**

plugins:
  - serverless-haskell
