service: fraudstop

provider:
  name: aws

functions:
  fraudstop-func:
    runtime: haskell
    handler: fraudstop.fraudstop-exe
    iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

  letter-func:
    runtime: nodejs10.x
    handler: letter.handler

plugins:
  - serverless-haskell
