service: fraudstop

provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  fraudstop-func:
    runtime: haskell
    handler: fraudstop.fraudstop-exe
    events:
      - http:
          integration: lambda-proxy
          path: /{x}
          method: POST
          cors: true
    timeout: 10
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
      SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
      DOCSAWAY_EMAIL: ${env:DOCSAWAY_EMAIL}
      DOCSAWAY_KEY: ${env:DOCSAWAY_KEY}
      SALT: ${env:SALT}

  letter-func:
    runtime: nodejs10.x
    handler: letter.handler

package:
  include:
    - node_modules/**

plugins:
  - serverless-haskell
